--Explanation:
--JOIN InvoiceDetails with Products:

--The query joins the InvoiceDetails table with the Products table on StockCode to access the product description and other details.
--Calculate Total Quantity Sold:

--SUM(id.Quantity) AS TotalQuantitySold: This calculates the total quantity sold for each product by summing the quantity values from InvoiceDetails.
--Group by Product Description:

--GROUP BY p.Description: Groups the results by product description so that the total quantity sold is calculated for each unique product.
--Order by Total Quantity Sold:

--ORDER BY TotalQuantitySold DESC: Orders the products by the total quantity sold in descending order, showing the most popular products first.


SELECT 
    p.StockCode, 
    p.Description, 
    SUM(id.Quantity) AS TotalQuantitySold,          -- Total quantity sold of each product
    SUM(id.Quantity * p.UnitPrice) AS TotalRevenue, -- Total revenue generated by each product
    AVG(p.UnitPrice) AS AverageUnitPrice,           -- Average unit price of the product
    COUNT(DISTINCT id.InvoiceNo) AS NumberOfInvoices -- Number of distinct invoices this product appears in
FROM 
    InvoiceDetails id
JOIN 
    Products p ON id.StockCode = p.StockCode
GROUP BY 
    p.StockCode, 
    p.Description
HAVING 
    SUM(id.Quantity) > 0 
ORDER BY 
    TotalRevenue DESC,    
    TotalQuantitySold DESC 
LIMIT 20;                  